<?php
if (!Mage::getStoreConfigFlag('payment/mollie_creditcard/use_components')) {
    return;
}
?>

<?php
$code = $this->getMethodCode();
?>
<div class="form-list" id="payment_form_<?php echo $this->escapeHtml($code) ?>" style="display:none">
    <div class="card-container">
        <label for="card-holder"><?php echo __('Card Holder'); ?></label>
        <div id="card-holder"></div>
        <div id="card-holder-error" class="component-error"></div>

        <label for="card-number"><?php echo __('Card Number'); ?></label>
        <div id="card-number"></div>
        <div id="card-number-error" class="component-error"></div>

        <label for="expiry-date"><?php echo __('Expiry Date'); ?></label>
        <div id="expiry-date"></div>
        <div id="expiry-date-error" class="component-error"></div>

        <label for="verification-code"><?php echo __('Verification Code'); ?></label>
        <div id="verification-code"></div>
        <div id="verification-code-error" class="component-error"></div>
    </div>
</div>

<input type="hidden" name="cardToken" />

<script>mollieComponentsInstance.mount();</script>
