<?php
/**
 * Copyright (c) 2012-2019, Mollie B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * @category    Mollie
 * @package     Mollie_Mpm
 * @author      Mollie B.V. (info@mollie.nl)
 * @copyright   Copyright (c) 2012-2019 Mollie B.V. (https://www.mollie.nl)
 * @license     http://www.opensource.org/licenses/bsd-license.php  BSD-License 2
 */
$code = $this->getMethodCode();
$method = $this->getMethodByCode($code);
?>
<?php if (!empty($method->issuers) && ($listType = $this->getIssuerListType($code))): ?>
    <ul class="form-list" id="payment_form_<?php echo $this->escapeHtml($code) ?>" style="display:none">
        <li>
            <label for="<?php echo $code ?>_issuer">
                <?php echo $this->getIssuerTitle($code); ?>
            </label>
            <span class="input-box">
                <?php if ($listType == 'dropdown'): ?>
                    <select name="<?php echo $code; ?>_issuer" id="<?php echo $code; ?>_issuer" class="input-text">
                        <option value=""><?php echo $this->__('Please select'); ?></option>
                        <?php foreach ($method->issuers() as $issuer): ?>
                            <option value="<?php echo htmlspecialchars($issuer->id); ?>">
                                <?php echo htmlspecialchars($issuer->name); ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
                <?php if ($listType == 'radio'): ?>
                    <ul>
                    <?php foreach ($this->sortIssuers($method->issuers()) as $issuer): ?>
                        <li>
                            <label>
                                <input type="radio" name="<?php echo $code; ?>_issuer" value="<?php echo htmlspecialchars($issuer->id); ?>" id="issuer_<?php echo htmlspecialchars($issuer->id); ?>" class="radio">
                                <img src="<?php echo $issuer->image->size2x; ?>" class="payment-issuer-icon"/>
                                <?php echo htmlspecialchars($issuer->name); ?>
                            </label>
                        </li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
             </span>
        </li>
    </ul>
<?php endif; ?>
