<?php
/**
 * Copyright (c) 2012-2019, Mollie B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * - Redistributions of source code must retain the above copyright notice,
 *   this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
 * DAMAGE.
 *
 * @category    Mollie
 * @package     Mollie_Mpm
 * @author      Mollie B.V. (info@mollie.nl)
 * @copyright   Copyright (c) 2012-2019 Mollie B.V. (https://www.mollie.nl)
 * @license     http://www.opensource.org/licenses/bsd-license.php  BSD-License 2
 */
?>
<?php
/**
 * @see Mollie_Mpm_Block_Payment_Info_Paymentlink
 */
$status = $this->getPaymentStatus();
?>
    <div class="mollie-method">
        <p>
            <?php if ($img = $this->getPaymentImage()): ?>
                <img src="<?= $img ?>"/>
            <?php endif; ?>
            <?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?>
        </p>
        <table class="form-list">
            <?php if ($checkoutType = $this->getCheckoutType()): ?>
                <tr>
                    <td class="label"><?= $this->__('Checkout Type'); ?></td>
                    <td class="value"><?= ucfirst($checkoutType); ?></td>
                </tr>
            <?php endif; ?>
            <?php if (($checkoutUrl = $this->getCheckoutUrl()) && ($status == 'created' || $status == 'open')): ?>
                <tr>
                    <td class="label"><?= $this->__('Checkout Url'); ?></td>
                    <td class="value"><?= $checkoutUrl; ?></td>
                </tr>
            <?php endif; ?>
            <?php if (($expiresAt = $this->getExpiresAt()) && ($status == 'created' || $status == 'open')): ?>
                <tr>
                    <td class="label"><?= $this->__('Valid Until'); ?></td>
                    <td class="value"><?= $expiresAt; ?></td>
                </tr>
            <?php endif; ?>
            <?php if ($status): ?>
                <tr>
                    <td class="label"><?= __('Payment Status'); ?></td>
                    <td class="value">
                        <?= ucfirst($status); ?>
                        <?php if ($this->isKlarnaMethod() && $status == 'authorized'): ?>
                            <?= $this->__('<a href="#" class="mollie-tooltip">(i)<span>Please ship order to capture Klarna payment</span></a>'); ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endif; ?>
        </table>
    </div>
<?php echo $this->getChildHtml() ?>