<div class="fieldset">
	<p>
		<strong><?php echo $this->__('BELANGERIJK!'); ?></strong>
		<br/>
		Vergeet niet de cache te verwijderen! Ga naar: <strong><?php echo $this->__('<a href="%s">Systeem > Cache Beheer</a>', $this->getUrl('adminhtml/cache')); ?></strong> om de cache te verwijderen.
	</p>
	<br/>
	<p>
		<?php
			if (is_array(Mage::Helper('mpm/data')->getModuleStatus()))
			{
				foreach (Mage::Helper('mpm/data')->getModuleStatus() as $file) {
					echo "Bestand bestaat niet: '$file'<br/>";
				}
			} else {
				echo Mage::Helper('mpm/data')->getModuleStatus();
			}
		?>
	</p>
	<br/>
	<p>
		<ul>
			<li>- Uw <a href="https://www.mollie.nl/beheer" title="Mollie Beheer">Mollie Account Beheer</a></li>
			<li>- Uw <a href="https://www.mollie.nl/beheer/account/" title="Profile">Mollie PartnerID</a></li>
			<li>- Uw <a href="https://www.mollie.nl/beheer/betaaldiensten/profielen/" title="Mollie Beheer">Mollie Profielen</a></li>
			<li>- Versie: v<?php echo(Mage::Helper('mpm/data')->getModuleVersion()); ?></li>
			<li>- Support: <a href="https://www.mollie.nl/bedrijf/contact" title="Support Contact">Mollie B.V.</a></li>
		</ul>
	</p>
</div>