<?php
$core = Mage::helper('core');
$methods = Mage::helper('mpm/api')->methods;
$message = $core->__('Your Mollie Account is reachable from the Magento store, but <a href="https://www.mollie.nl/beheer/diensten/">seems to lack payment methods</a>.');
if (is_string($methods)) {
	$message = $methods;
	$methods = array();
}
$method_count = 0;
foreach ($methods as $method)
{
	if ($method['available'])
	{
		$method_count++;
	}
}

if (strlen($code = Mage::getSingleton('adminhtml/config_data')->getStore()))
{
	$storeId = Mage::getModel('core/store')->load($code)->getId();
}
elseif (strlen($code = Mage::getSingleton('adminhtml/config_data')->getWebsite()))
{
	$websiteId = Mage::getModel('core/website')->load($code)->getId();
	$storeId = Mage::app()->getWebsite($websiteId)->getDefaultStore()->getId();
}
else
{
	$storeId = 0;
}

$countries = Mage::getModel('adminhtml/system_config_source_country')->toOptionArray();
?>
	<tr><td>
		<b><?php echo $core->__('Api Key'); ?></b><br />
		<?php echo $core->__('You can find your <i>Api Key</i> in your <a href="https://www.mollie.nl/beheer/account/profielen/" title="Mollie Profiles">Mollie Profile</a>.');?><br />
		<br />

		<b><?php echo $core->__('Payment methods'); ?></b><br />
		<?php if ($method_count > 0): ?>
			<?php
			if ($method_count !== 1)
			{
				echo sprintf($core->__('%d payment methods available:'), $method_count);
			}
			else
			{
				echo $core->__('One payment method available:');
			}
			?>
			<table>
				<tr>
                    <th><?php echo $core->__('Title');?></th>
                    <th style="width: 40px"></th>
					<th style="width:150px;"><?php echo $core->__('Description');?></th>
					<th style="width:150px;"><?php echo $core->__('Minimum Amount');?></th>
					<th style="width:150px;"><?php echo $core->__('Maximum Amount');?></th>
					<th><?php if($storeId == 0) : echo $core->__('Allowed countries'); endif;?></th>
					<th style="width:40px;"><?php echo $core->__('Sort Order');?></th>
				</tr>
				<?php
				foreach($methods as $key => $method):
					$allowSpecific = Mage::helper('mpm/data')->getConfig('mpm_void_' . str_pad($key, 2, "0", STR_PAD_LEFT), 'allowspecific', $storeId);
					$specificCountry = explode(',', Mage::helper('mpm/data')->getConfig('mpm_void_' . str_pad($key, 2, "0", STR_PAD_LEFT), 'specificcountry'), $storeId);
					$sortOrder = Mage::helper('mpm/data')->getConfig('mpm_void_' . str_pad($key, 2, "0", STR_PAD_LEFT), 'sort_order', $storeId);
					$title = Mage::helper('mpm/data')->getConfig('mpm_void_' . str_pad($key, 2, "0", STR_PAD_LEFT), 'title', $storeId);

					if ($method['available']):
						?>
						<tr>
							<td class="value">
								<input type="text"
									   name="groups[mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>][fields][title][value]"
									   value="<?php echo $title ?: $core->__($method['description']); ?>"
									   class="input-text disabled"
								/>
							</td>
							<td class="use-default">
								<input id="payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_apikey_inherit"
									   name="groups[mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>][fields][title][inherit]"
									   type="checkbox" value="1"
									   class="checkbox config-inherit"
									   checked="checked"
									   onclick="toggleValueElements(this, Element.previous(this.parentNode))">
							</td>

							<td><?php echo $core->__($method['description']); ?></td>
							<td>&euro; <?php echo number_format($method['amount']->minimum, 2); ?></td>
							<td>&euro; <?php echo number_format($method['amount']->maximum, 2); ?></td>
							<td class="value">
								<?php if ($storeId == 0): ?>
									<select id="payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_allowspecific"
											name="groups[mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>][fields][allowspecific][value]"
											class=" select">
										<option value="0" <?php if(!$allowSpecific): ?>selected="selected"<?php endif;?>><?php echo $core->__('All Allowed Countries');?></option>
										<option value="1" <?php if($allowSpecific): ?>selected="selected"<?php endif;?>><?php echo $core->__('Specific Countries');?></option>
									</select>
									<script type="text/javascript">
										Event.observe('payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_allowspecific', 'change', function(){
											specific=$('payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_allowspecific').value;
											$('payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_specificcountry').disabled = (!specific || specific!=1);
											$('payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_specificcountry').toggle();
										});
									</script>
									<br/><br/>
									<select id="payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_specificcountry"
											name="groups[mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>][fields][specificcountry][value][]"
											class=" select multiselect"
											size="10"
											<?php if(!$allowSpecific): ?>disabled="disabled"<?php endif; ?>
											multiple="multiple"
											<?php if(!$allowSpecific): ?>style="display: none;"<?php endif; ?>
									<?php foreach($countries as $country): ?>
									<?php $selected = (in_array($country['value'], $specificCountry) || $country['value'] == $specificCountry) ? true : false; ?>
									<option value="<?php echo $country['value']; ?>" <?php if($allowSpecific && $selected): ?>selected="selected"<?php endif; ?>>
										<?php echo $country['label']; ?>
									</option>
								<?php endforeach; ?>
									</select>
								<?php endif; ?>
							</td>
							<td>
								<input id="payment_mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>_sort_order"
									   name="groups[mpm_void_<?php echo str_pad($key, 2, "0", STR_PAD_LEFT); ?>][fields][sort_order][value]"
									   value="<?php echo $sortOrder; ?>"
									   style="width:40px;" />
							</td>
						</tr>
					<?php
					endif;
				endforeach;
				?>
			</table>
		<?php else:
			echo $core->__('No payment methods available for this account.<br />Reason: ') . $message . '<br />';
		endif; ?>
		<br />

		<b><?php echo $core->__('Version'); ?></b><br />
		<?php echo sprintf($core->__('This is version &quot;v%s&quot; of Mollie&lsquo;s Magento module.'), $this->escapeHtml(Mage::Helper('mpm/data')->getModuleVersion())); ?><br />
		<?php echo Mage::Helper('mpm/data')->_getUpdateMessage(); ?><br />
		<br />
		<?php echo Mage::Helper('mpm/data')->getModuleStatus($method_count, 16); ?><br />
		<br />
		<?php echo $core->__('If you have any questions or suggestions, please contact <a href="https://www.mollie.nl/bedrijf/contact" title="Mollie Support Contact">Mollie B.V.</a>');?><br />
		<br/>
		<img src="https://www.mollie.nl/images/badge-powered-big.png" alt='Mollie' /><br/>
		<script type="text/javascript">
			if (!window.pushDownPaypal) window.pushDownPaypal = function ()
			{
				var i, notice = document.getElementsByClassName('paypal-payment-notice');
				for (i = 0; i < notice.length; i++)
				{
					notice[i].style.marginTop = '50px';
				}
			}
			if (document.addEventListener)
			{
				document.addEventListener("DOMContentLoaded", pushDownPaypal, false);
			}
			else if (document.attachEvent)
			{
				document.attachEvent("onreadystatechange", pushDownPaypal);
			}
		</script>
	</td></tr>