<?php
$core = Mage::helper('core');
$methods = Mage::Helper('mpm/api')->methods;
$message = $core->__('Your Mollie Account is reachable from the Magento store, but <a href="http://mollie.dev/beheer/diensten/">seems to lack payment methods</a>.');
if (is_string($methods)) {
	$message = $methods;
	$methods = array();
}
$method_count = 0;
foreach ($methods as $method)
{
	if ($method['available'])
	{
		$method_count++;
	}
}
?>
	<tr><td>
		<b><?php echo $core->__('Api Key'); ?></b><br />
		<?php echo $core->__('You can find your <i>Api Key</i> in your <a href="https://www.mollie.nl/beheer/account/profielen/" title="Mollie Profiles">Mollie Profile</a>.');?><br />
		<br />

		<b><?php echo $core->__('Webhook'); ?></b><br />
		<?php echo $core->__('Your webhook URL is:'); ?><br />
		<input id="webhook" value="<?php echo $this->escapeHtml(Mage::helper('mpm/api')->getWebhookURL()); ?>" readonly onclick="this.select();" /><br />
		<script type="text/javascript">
			var el = document.getElementById('webhook');
			el.size = el.value.length + 20;
		</script>
		<br />

		<b><?php echo $core->__('Payment methods'); ?></b><br />
		<?php if ($method_count > 0): ?>
			<?php
			if ($method_count !== 1)
			{
				echo sprintf($core->__('%d payment methods available:'), $method_count);
			}
			else
			{
				echo $core->__('One payment method available:');
			}
			?>
			<table>
				<tr>
					<th style="width:150px;"><?php echo $core->__('Description');?></th>
					<th style="width:150px;"><?php echo $core->__('Minimum Amount');?></th>
					<th style="width:150px;"><?php echo $core->__('Maximum Amount');?></th>
				</tr>
				<?php
				foreach($methods as $method):
					if ($method['available']):
						?>
						<tr>
							<td><?php echo $core->__($method['description']); ?></td>
							<td>&euro; <?php echo number_format($method['amount']->minimum, 2); ?></td>
							<td>&euro; <?php echo number_format($method['amount']->maximum, 2); ?></td>
						</tr>
					<?php
					endif;
				endforeach;
				?>
			</table>
		<?php else:
			echo $core->__('No payment methods available for this account.<br />Reason: ') . $message . '<br />';
		endif; ?>
		<br />

		<b><?php echo $core->__('Version'); ?></b><br />
		<?php echo sprintf($core->__('This is version &quot;v%s&quot; of Mollie&lsquo;s Magento module.'), $this->escapeHtml(Mage::Helper('mpm/data')->getModuleVersion())); ?><br />
		<?php echo Mage::Helper('mpm/data')->_getUpdateMessage('https://github.com/mollie/Magento'); ?><br />
		<br />
		<?php echo Mage::Helper('mpm/data')->getModuleStatus($method_count, 32); ?><br />
		<br />
		<?php echo $core->__('If you have any questions or suggestions, please contact <a href="https://www.mollie.nl/bedrijf/contact" title="Mollie Support Contact">Mollie B.V.</a>');?><br />
		<br/>
		<img src="https://www.mollie.nl/images/badge-powered-big.png" alt='Mollie' /><br/>
		<script type="text/javascript">
			if (!window.pushDownPaypal) window.pushDownPaypal = function ()
			{
				var i, notice = document.getElementsByClassName('paypal-payment-notice');
				for (i = 0; i < notice.length; i++)
				{
					notice[i].style.marginTop = '50px';
				}
			}
			if (document.addEventListener)
			{
				document.addEventListener("DOMContentLoaded", pushDownPaypal, false);
			}
			else if (document.attachEvent)
			{
				document.attachEvent("onreadystatechange", pushDownPaypal);
			}
		</script>
	</td></tr>