<?php
	// Get Payment code ( mpm_idl ) //
	$_code = $this->getMethodCode();
	// Fetch all iDEAL banks
	/** @var Mollie_Mpm_Helper_Idl $helper */
	$helper = Mage::Helper('mpm/idl');
	$_banks = $helper->getBanks();

	if (!$_banks):
		?>
			<span style="color: red;">Error in iDEAL module: <?php echo $this->escapeHtml($helper->getErrorMessage());?></span>
		<?php
	endif;
?>
<ul class="form-list" id="payment_form_<?php echo $this->escapeHtml($_code) ?>" style="display:none;">
	<li>
		<label for="<?php echo $this->escapeHtml($_code) ?>_bank_id" class="required"><em>*</em><?php echo $this->__('Selecteer uw bank:') ?></label>
		<span class="input-box">
			<select name="payment[bankid]" class="required-entry input-text" id="<?php echo $this->escapeHtml($_code) ?>_bank_id">
				<option value=''><?php echo $this->__('Selecteer uw bank:') ?></option>
				<?php foreach ($_banks as $bank_id => $bank_name): ?>
					<option value="<?php echo $this->escapeHtml($bank_id) ?>"><?php echo $this->escapeHtml($bank_name) ?></option>
				<?php endforeach; ?>
			</select>
		</span>
	</li>
</ul>